# -*- coding: utf-8 -*-
"""Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aH_j5TaHXMkeW0lB2WxUckM0xBG98CxE

1. Split this string
"""

s= "Hi there sam! "
s.split()

"""2. Use .format() to print the following stiring

"""

planet="Earth"
diameter=12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))

"""3. In the nest dictionary grab the word "hello"
"""

d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}



"""Numpy

"""

[] import as np

"""4.1 Create an array of 10 Zeros?


"""

import numpy as np
x=np.array([0,0,0,0,0,0,0,0,0,0])
print(x)

"""4.2 Create an array of 10 fives?"""

import numpy as np
y=np.array([5,5,5,5,5,5,5,5,5,5])
print(y)

"""5. Create an arrey of all the even integers from 20 to 35"""

i = 20
while i < 35:
  print(i)
  i += 2

"""6. Create a 3x3 matrix with values ranging from 0 to 8"""

b=np.arange(0,9,1)
b.reshape(3,3)

"""7. Concatenate a and b

a=np.array([1,2,3]),b=np.array([4,5,6])
"""

a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

"""Pandas

8. Create a dataframe with 3 rows and 2 cloumns
"""

import pandas as pd

import pandas as pd
data = {
  "calories": [4, 8 , 3 ],
  "duration": [4 , 5 ,6  ]
}
df = pd.DataFrame(data)
print(df)

"""9. Generate the series of dates from 1st jan,2023 to 10th feb,2023"""

import pandas as pd
pd.date_range("01-01-2023","10-02-2023")

"""10. Create 2D list to DataJFrame

lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
"""

lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]